name: CI

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Install packages
        run: yarn install

      - name: Build static site
        run: yarn build

      - name: Deploy to bunny.net
        uses: Serpentiel/FTP-Deploy-Action@master
        with:
          server: storage.bunnycdn.com
          username: ${{ secrets.bunnycdn_username }}
          password: ${{ secrets.bunnycdn_password }}
          local-dir: ./dist/
          server-dir: ${{ secrets.bunnycdn_server_dir }}

      - name: 'Purge bunny.net Pull Zone''s cache'
        uses: fjogeleit/http-request-action@master
        with:
          url: https://api.bunny.net/pullzone/${{ secrets.bunnycdn_pullzone_id }}/purgeCache
          method: POST
          customHeaders: '{"AccessKey": "${{ secrets.bunnycdn_accesskey }}"}'
